project:
  type: website

website:
  title: ""
  site-url: https://aiguoqing1984.github.io/pkd-lab-website/
  navbar:
    pinned: true
    logo: images/logo.png
    search: false
    left:
      
      - text: Research
        href: research/research_index.qmd

      - text: Personnel
        href: Personnel.qmd

      - text: Publications
        href: Publications.qmd

      - text: News
        href: News.qmd

      - text: Contact
        href: Contact.qmd
format:
  html:
    anchor-sections: false
    css: styles.css




