project:
  type: website

website:
  title: "Song Lab"
  site-url: https://aiguoqing1984.github.io/pkd-lab-website/
  navbar:          
    pinned: true
    logo: images/logo1.png
    search: false
    left:
      - text: Research
        href: research.qmd
        
      - text: Personnel
        href: Personnel.qmd
        
      - text: Publications
        href: Publications.qmd

      - text: News
        href: News.qmd

      - text: Contact
        href: Contact.qmd
        
      - href: gallery.qmd
        text: Lab Gallery

      - href: test.qmd
        text: test
format:
  html:
    page-layout: full
    anchor-sections: false
    css: styles.css
    
    
    